### ISSUE TITLE
Add GPIO Image

### ISSUE THREAD

**Issue by ryanteck** [raspberrypilearning/screaming-jellybaby#6]
Would be handy to have an image of the GPIO pins to plug it into or a pin map. People may find it easier

**Comment by lurch** [comment]
There's now a pin map (so this issue could be closed) but part of the text says "The picture above shows the Raspberry Pi GPIO header pins; the diagram above the pins shows the pin numbers" whereas there's only a diagram and no picture.
And would it be better to use the images e.g. from https://github.com/raspberrypi/documentation/tree/master/usage/gpio-plus-and-raspi2 rather than using a Markdown-formatted table?

**Comment by MissPhilbin** [comment]
All markdown tables will be replaced with graphic images in the coming months.
